function out = f_equationsYD(l)
    if (-pi <= l.pr.phi && l.pr.phi <= -2*pi/3)
    out = l.eq.YD.eq1.f(l.pr.L1,l.pr.L2,l.pr.Ldab,l.pr.M,l.pr.Vi,l.pr.d,l.pr.fs,l.pr.phi, ...
        l.tr.ki,l.tr.b,l.tr.a,l.tr.Ac,l.tr.N,l.tr.Ve, ...   
        l.L.ki,l.L.b,l.L.a,l.L.Ac,l.L.N,l.L.Ve);
    elseif (-2*pi/3 <= l.pr.phi && l.pr.phi <= -pi/3)
    out = l.eq.YD.eq2.f(l.pr.L1,l.pr.L2,l.pr.Ldab,l.pr.M,l.pr.Vi,l.pr.d,l.pr.fs,l.pr.phi, ...
        l.tr.ki,l.tr.b,l.tr.a,l.tr.Ac,l.tr.N,l.tr.Ve, ...   
        l.L.ki,l.L.b,l.L.a,l.L.Ac,l.L.N,l.L.Ve);
    elseif (-pi/3 <= l.pr.phi && l.pr.phi <= 0)
    out = l.eq.YD.eq3.f(l.pr.L1,l.pr.L2,l.pr.Ldab,l.pr.M,l.pr.Vi,l.pr.d,l.pr.fs,l.pr.phi, ...
        l.tr.ki,l.tr.b,l.tr.a,l.tr.Ac,l.tr.N,l.tr.Ve, ...   
        l.L.ki,l.L.b,l.L.a,l.L.Ac,l.L.N,l.L.Ve);
    elseif (0 <= l.pr.phi && l.pr.phi <= pi/3)
    out = l.eq.YD.eq4.f(l.pr.L1,l.pr.L2,l.pr.Ldab,l.pr.M,l.pr.Vi,l.pr.d,l.pr.fs,l.pr.phi, ...
        l.tr.ki,l.tr.b,l.tr.a,l.tr.Ac,l.tr.N,l.tr.Ve, ...   
        l.L.ki,l.L.b,l.L.a,l.L.Ac,l.L.N,l.L.Ve);
    elseif (pi/3 <= l.pr.phi && l.pr.phi <= 2*pi/3)
    out = l.eq.YD.eq5.f(l.pr.L1,l.pr.L2,l.pr.Ldab,l.pr.M,l.pr.Vi,l.pr.d,l.pr.fs,l.pr.phi, ...
        l.tr.ki,l.tr.b,l.tr.a,l.tr.Ac,l.tr.N,l.tr.Ve, ...   
        l.L.ki,l.L.b,l.L.a,l.L.Ac,l.L.N,l.L.Ve);
    elseif (2*pi/3 <= l.pr.phi && l.pr.phi <= pi)
    out = l.eq.YD.eq6.f(l.pr.L1,l.pr.L2,l.pr.Ldab,l.pr.M,l.pr.Vi,l.pr.d,l.pr.fs,l.pr.phi, ...
        l.tr.ki,l.tr.b,l.tr.a,l.tr.Ac,l.tr.N,l.tr.Ve, ...   
        l.L.ki,l.L.b,l.L.a,l.L.Ac,l.L.N,l.L.Ve);
    end
end